name: CI (with KernelSU)

on:
  workflow_dispatch:
    inputs:
      kernel-branch:
        required: true
        type: string
      release-type:
        required: true
        type: choice
        options:
        - kaihatsu
        - seishiki
        default: 'kaihatsu'
      device-codename:
        required: true
        type: choice
        options:
        - citrus
        - lime

jobs:
  build-kernel:
    name: Build Kernel with KernelSU
    runs-on: ubuntu-latest
    steps:
      - name: Display parameters
        uses: m-s-abeer/update-gha-summary-with-workflow-inputs@v1

      - name: Build
        uses: frstprjkt/kernel_actions@main
        with:
          kernel-url: https://github.com/frstprjkt/valeryn_xiaomi_sm6115
          kernel-branch: ${{ github.event.inputs.kernel-branch }}

          arch: arm64
          defconfig: vendor/bengal-perf_defconfig vendor/xiaomi/${{ github.event.inputs.device-codename }}.config
          extra-args: LLVM=1 LLVM_IAS=1 KBUILD_BUILD_USER=valeryn

          ksu: true
          ksu-url: https://github.com/backslashxx/KernelSU
          ksu-version: master

          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r563880c

          anykernel3: true
          anykernel3-url: https://github.com/frstprjkt/AnyKernel3
          anykernel3-branch: ${{ github.event.inputs.device-codename }}

          package-name: valeryn-ksu_$(date +%d%H%M)_${{ github.event.inputs.device-codename }}-${{ github.event.inputs.release-type }}
